version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    depends_on:
      - database  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    command: npm start  


  database:
    image: postgres:latest  
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: psql
    ports:
      - "5432:5432"  


